export const cars = [
  {
    id: 1,
    image: "/F1.jpeg",
    name: "Ferrari Roma",
    type: "Sports",
    price: 2940,
    durationPrice: 4900,
    specs: {
      seats: 2,
      horsepower: 612,
      engine: "3.9L V8",
      acceleration: 3.4, // 0-100 in seconds
    },
  },
  {
    id: 2,
    image: "/F2.jpeg",
    name: "Lamborghini Urus",
    type: "SUV",
    price: 2580,
    durationPrice: 4300,
    specs: {
      seats: 5,
      horsepower: 641,
      engine: "4.0L V8",
      acceleration: 3.6,
    },
  },
  {
    id: 3,
    image: "/F3.jpeg",
    name: "McLaren Artura",
    type: "Sports",
    price: 3200,
    durationPrice: 5400,
    specs: {
      seats: 2,
      horsepower: 671,
      engine: "3.0L V6 Hybrid",
      acceleration: 3.0,
    },
  },
  {
    id: 4,
    image: "/F4.jpeg",
    name: "Rolls-Royce Cullinan",
    type: "Luxury",
    price: 2800,
    durationPrice: 4800,
    specs: {
      seats: 5,
      horsepower: 563,
      engine: "6.75L V12",
      acceleration: 5.2,
    },
  },
  {
    id: 5,
    image: "/F5.jpeg",
    name: "McLaren 750S Spider",
    type: "Convertible",
    price: 2600,
    durationPrice: 4500,
    specs: {
      seats: 2,
      horsepower: 740,
      engine: "4.0L V8",
      acceleration: 2.8,
    },
  },
  {
    id: 6,
    image: "/F6.jpeg",
    name: "Mercedes G63 Black 2025",
    type: "SUV",
    price: 2400,
    durationPrice: 4200,
    specs: {
      seats: 5,
      horsepower: 577,
      engine: "4.0L V8",
      acceleration: 4.5,
    },
  },
  {
    id: 7,
    image: "/F1.jpeg",
    name: "Audi A6",
    type: "Sedan",
    price: 450,
    durationPrice: 2700,
    specs: {
      seats: 5,
      horsepower: 335,
      engine: "3.0L V6",
      acceleration: 5.1,
    },
  },
  {
    id: 8,
    image: "/F2.jpeg",
    name: "Audi A3",
    type: "Sedan",
    price: 350,
    durationPrice: 2100,
    specs: {
      seats: 5,
      horsepower: 228,
      engine: "2.0L I4",
      acceleration: 5.8,
    },
  },
  {
    id: 9,
    image: "/F3.jpeg",
    name: "Audi RS3",
    type: "Sedan",
    price: 850,
    durationPrice: 5100,
    specs: {
      seats: 5,
      horsepower: 395,
      engine: "2.5L I5",
      acceleration: 3.8,
    },
  },
  {
    id: 10,
    image: "/F4.jpeg",
    name: "Audi RS6",
    type: "Sedan",
    price: 1500,
    durationPrice: 9000,
    specs: {
      seats: 5,
      horsepower: 591,
      engine: "4.0L V8",
      acceleration: 3.5,
    },
  },
  {
    id: 11,
    image: "/F5.jpeg",
    name: "Audi RSQ3",
    type: "SUV",
    price: 750,
    durationPrice: 4500,
    specs: {
      seats: 5,
      horsepower: 395,
      engine: "2.5L I5",
      acceleration: 4.1,
    },
  },
  {
    id: 12,
    image: "/F6.jpeg",
    name: "Audi RSQ8",
    type: "SUV",
    price: 1100,
    durationPrice: 6600,
    specs: {
      seats: 5,
      horsepower: 591,
      engine: "4.0L V8",
      acceleration: 3.8,
    },
  },
  {
    id: 13,
    image: "/F1.jpeg",
    name: "Audi RSQ8 Performance 2025",
    type: "SUV",
    price: 1500,
    durationPrice: 9000,
    specs: {
      seats: 5,
      horsepower: 631,
      engine: "4.0L V8",
      acceleration: 3.6,
    },
  },
  {
    id: 14,
    image: "/F2.jpeg",
    name: "Bentley Bentayga Azure",
    type: "Luxury",
    price: 2100,
    durationPrice: 12600,
    specs: {
      seats: 5,
      horsepower: 542,
      engine: "4.0L V8",
      acceleration: 4.5,
    },
  },
  {
    id: 15,
    image: "/F3.jpeg",
    name: "BMW X1",
    type: "SUV",
    price: 400,
    durationPrice: 2400,
    specs: {
      seats: 5,
      horsepower: 228,
      engine: "2.0L I4",
      acceleration: 5.6,
    },
  },
  {
    id: 16,
    image: "/F4.jpeg",
    name: "BMW X6 Competition",
    type: "SUV",
    price: 1400,
    durationPrice: 8400,
    specs: {
      seats: 5,
      horsepower: 617,
      engine: "4.4L V8",
      acceleration: 3.8,
    },
  },
  {
    id: 17,
    image: "/F5.jpeg",
    name: "BMW X7",
    type: "SUV",
    price: 1300,
    durationPrice: 7800,
    specs: {
      seats: 7,
      horsepower: 375,
      engine: "3.0L I6",
      acceleration: 5.8,
    },
  },
  {
    id: 18,
    image: "/F6.jpeg",
    name: "BMW XM",
    type: "SUV",
    price: 1900,
    durationPrice: 11400,
    specs: {
      seats: 5,
      horsepower: 644,
      engine: "4.4L V8 Hybrid",
      acceleration: 4.1,
    },
  },
  {
    id: 19,
    image: "/F1.jpeg",
    name: "Bugatti Chiron",
    type: "Sports",
    price: 35000,
    durationPrice: 210000,
    specs: {
      seats: 2,
      horsepower: 1500,
      engine: "8.0L W16",
      acceleration: 2.4,
    },
  },
  {
    id: 20,
    image: "/F2.jpeg",
    name: "Cadillac Escalade V Series",
    type: "SUV",
    price: 2000,
    durationPrice: 12000,
    specs: {
      seats: 7,
      horsepower: 682,
      engine: "6.2L V8",
      acceleration: 4.4,
    },
  },
  {
    id: 21,
    image: "/F3.jpeg",
    name: "Chevrolet Corvette",
    type: "Sports",
    price: 1200,
    durationPrice: 7200,
    specs: {
      seats: 2,
      horsepower: 490,
      engine: "6.2L V8",
      acceleration: 2.9,
    },
  },
  {
    id: 22,
    image: "/F4.jpeg",
    name: "Ferrari 296 GTS",
    type: "Convertible",
    price: 3500,
    durationPrice: 21000,
    specs: {
      seats: 2,
      horsepower: 819,
      engine: "3.0L V6 Hybrid",
      acceleration: 2.9,
    },
  },
  {
    id: 23,
    image: "/F5.jpeg",
    name: "Ferrari 488 Spider",
    type: "Convertible",
    price: 2800,
    durationPrice: 16800,
    specs: {
      seats: 2,
      horsepower: 661,
      engine: "3.9L V8",
      acceleration: 3.0,
    },
  },
  {
    id: 24,
    image: "/F6.jpeg",
    name: "Ferrari F8 Spider",
    type: "Convertible",
    price: 3100,
    durationPrice: 18600,
    specs: {
      seats: 2,
      horsepower: 710,
      engine: "3.9L V8",
      acceleration: 2.9,
    },
  },
  {
    id: 25,
    image: "/F1.jpeg",
    name: "Ferrari Portofino",
    type: "Convertible",
    price: 2500,
    durationPrice: 15000,
    specs: {
      seats: 4,
      horsepower: 591,
      engine: "3.9L V8",
      acceleration: 3.5,
    },
  },
  {
    id: 26,
    image: "/F2.jpeg",
    name: "Lamborghini Evo Spyder",
    type: "Convertible",
    price: 3300,
    durationPrice: 19800,
    specs: {
      seats: 2,
      horsepower: 631,
      engine: "5.2L V10",
      acceleration: 3.1,
    },
  },
  {
    id: 27,
    image: "/F3.jpeg",
    name: "Lamborghini Huracán STO",
    type: "Sports",
    price: 4000,
    durationPrice: 24000,
    specs: {
      seats: 2,
      horsepower: 630,
      engine: "5.2L V10",
      acceleration: 3.0,
    },
  },
  {
    id: 28,
    image: "/F4.jpeg",
    name: "Range Rover Vogue",
    type: "SUV",
    price: 1800,
    durationPrice: 10800,
    specs: {
      seats: 5,
      horsepower: 395,
      engine: "3.0L I6",
      acceleration: 5.8,
    },
  },
  {
    id: 29,
    image: "/F5.jpeg",
    name: "Range Rover Defender",
    type: "SUV",
    price: 1400,
    durationPrice: 8400,
    specs: {
      seats: 5,
      horsepower: 395,
      engine: "3.0L I6",
      acceleration: 6.1,
    },
  },
  {
    id: 30,
    image: "/F6.jpeg",
    name: "Mercedes Benz S500",
    type: "Luxury",
    price: 1800,
    durationPrice: 10800,
    specs: {
      seats: 5,
      horsepower: 429,
      engine: "3.0L I6",
      acceleration: 4.9,
    },
  },
  {
    id: 31,
    image: "/F1.jpeg",
    name: "Mercedes Maybach",
    type: "Luxury",
    price: 2500,
    durationPrice: 15000,
    specs: {
      seats: 4,
      horsepower: 496,
      engine: "4.0L V8",
      acceleration: 4.8,
    },
  },
  {
    id: 32,
    image: "/F2.jpeg",
    name: "Mercedes V Class",
    type: "Luxury",
    price: 1200,
    durationPrice: 7200,
    specs: {
      seats: 7,
      horsepower: 190,
      engine: "2.0L I4 Diesel",
      acceleration: 10.5,
    },
  }
];
