export const cars = [
  {
    id: 1,
    image: "/F1.jpeg",
    name: "Ferrari Roma",
    price: 2940,
    durationPrice: 4900,
    specs: {
      seats: 2,
      horsepower: 612,
      engine: "3.9L V8",
      acceleration: 3.4, // 0-100 in seconds
    },
  },
  {
    id: 2,
    image: "/F2.jpeg",
    name: "Lamborghini Urus",
    price: 2580,
    durationPrice: 4300,
    specs: {
      seats: 5,
      horsepower: 641,
      engine: "4.0L V8",
      acceleration: 3.6,
    },
  },
  {
    id: 3,
    image: "/F3.jpeg",
    name: "McLaren Artura",
    price: 3200,
    durationPrice: 5400,
    specs: {
      seats: 2,
      horsepower: 671,
      engine: "3.0L V6 Hybrid",
      acceleration: 3.0,
    },
  },
  {
    id: 4,
    image: "/F4.jpeg",
    name: "Rolls-Royce Cullinan",
    price: 2800,
    durationPrice: 4800,
    specs: {
      seats: 5,
      horsepower: 563,
      engine: "6.75L V12",
      acceleration: 5.2,
    },
  },
  {
    id: 5,
    image: "/F5.jpeg",
    name: "McLaren 750S Spider",
    price: 2600,
    durationPrice: 4500,
    specs: {
      seats: 2,
      horsepower: 740,
      engine: "4.0L V8",
      acceleration: 2.8,
    },
  },
  {
    id: 6,
    image: "/F6.jpeg",
    name: "Mercedes G63 Black 2025",
    price: 2400,
    durationPrice: 4200,
    specs: {
      seats: 5,
      horsepower: 577,
      engine: "4.0L V8",
      acceleration: 4.5,
    },
  },
  {
    id: 7,
    image: "/F1.jpeg",
    name: "Audi A6",
    price: 450,
    durationPrice: 2700,
    specs: {
      seats: 5,
      horsepower: 335,
      engine: "3.0L V6",
      acceleration: 5.1,
    },
  },
  {
    id: 8,
    image: "/F2.jpeg",
    name: "Audi A3",
    price: 350,
    durationPrice: 2100,
    specs: {
      seats: 5,
      horsepower: 228,
      engine: "2.0L I4",
      acceleration: 5.8,
    },
  },
  {
    id: 9,
    image: "/F3.jpeg",
    name: "Audi RS3",
    price: 850,
    durationPrice: 5100,
    specs: {
      seats: 5,
      horsepower: 395,
      engine: "2.5L I5",
      acceleration: 3.8,
    },
  },
  {
    id: 10,
    image: "/F4.jpeg",
    name: "Audi RS6",
    price: 1500,
    durationPrice: 9000,
    specs: {
      seats: 5,
      horsepower: 591,
      engine: "4.0L V8",
      acceleration: 3.5,
    },
  },
  {
    id: 11,
    image: "/F5.jpeg",
    name: "Audi RSQ3",
    price: 750,
    durationPrice: 4500,
    specs: {
      seats: 5,
      horsepower: 395,
      engine: "2.5L I5",
      acceleration: 4.1,
    },
  },
  {
    id: 12,
    image: "/F6.jpeg",
    name: "Audi RSQ8",
    price: 1100,
    durationPrice: 6600,
    specs: {
      seats: 5,
      horsepower: 591,
      engine: "4.0L V8",
      acceleration: 3.8,
    },
  },
  {
    id: 13,
    image: "/F1.jpeg",
    name: "Audi RSQ8 Performance 2025",
    price: 1500,
    durationPrice: 9000,
    specs: {
      seats: 5,
      horsepower: 631,
      engine: "4.0L V8",
      acceleration: 3.6,
    },
  },
  {
    id: 14,
    image: "/F2.jpeg",
    name: "Bentley Bentayga Azure",
    price: 2100,
    durationPrice: 12600,
    specs: {
      seats: 5,
      horsepower: 542,
      engine: "4.0L V8",
      acceleration: 4.5,
    },
  },
  {
    id: 15,
    image: "/F3.jpeg",
    name: "BMW X1",
    price: 400,
    durationPrice: 2400,
    specs: {
      seats: 5,
      horsepower: 228,
      engine: "2.0L I4",
      acceleration: 5.6,
    },
  },
  {
    id: 16,
    image: "/F4.jpeg",
    name: "BMW X6 Competition",
    price: 1500,
    durationPrice: 9000,
    specs: {
      seats: 5,
      horsepower: 523,
      engine: "4.4L V8",
      acceleration: 4.2,
    },
  },
  {
    id: 17,
    image: "/F5.jpeg",
    name: "Corvette C8 Stingray Red 2025",
    price: 1100,
    durationPrice: 6600,
    specs: {
      seats: 2,
      horsepower: 495,
      engine: "6.2L V8",
      acceleration: 2.9,
    },
  },
  {
    id: 18,
    image: "/F6.jpeg",
    name: "Ferrari F8 Spyder",
    price: 3300,
    durationPrice: 19800,
    specs: {
      seats: 2,
      horsepower: 710,
      engine: "3.9L V8",
      acceleration: 2.9,
    },
  },
  {
    id: 19,
    image: "/F1.jpeg",
    name: "Golf R",
    price: 650,
    durationPrice: 3900,
    specs: {
      seats: 5,
      horsepower: 315,
      engine: "2.0L I4",
      acceleration: 4.7,
    },
  },
  {
    id: 20,
    image: "/F2.jpeg",
    name: "Lamborghini Huracan Evo Spyder Red and Yellow",
    price: 3600,
    durationPrice: 21600,
    specs: {
      seats: 2,
      horsepower: 630,
      engine: "5.2L V10",
      acceleration: 2.9,
    },
  },
  {
    id: 21,
    image: "/F3.jpeg",
    name: "Lamborghini Urus Performante 2024",
    price: 3500,
    durationPrice: 21000,
    specs: {
      seats: 5,
      horsepower: 666,
      engine: "4.0L V8",
      acceleration: 3.3,
    },
  },
  {
    id: 22,
    image: "/F4.jpeg",
    name: "Lamborghini Urus Red, Yellow and Green",
    price: 2400,
    durationPrice: 14400,
    specs: {
      seats: 5,
      horsepower: 641,
      engine: "4.0L V8",
      acceleration: 3.6,
    },
  },
  {
    id: 23,
    image: "/F5.jpeg",
    name: "Lamborghini Urus S 2024",
    price: 2800,
    durationPrice: 16800,
    specs: {
      seats: 5,
      horsepower: 657,
      engine: "4.0L V8",
      acceleration: 3.5,
    },
  },
  {
    id: 24,
    image: "/F6.jpeg",
    name: "Mercedes C300 2025",
    price: 450,
    durationPrice: 2700,
    specs: {
      seats: 5,
      horsepower: 255,
      engine: "2.0L I4",
      acceleration: 5.9,
    },
  },
  {
    id: 25,
    image: "/F1.jpeg",
    name: "Mercedes CLA 2025",
    price: 400,
    durationPrice: 2400,
    specs: {
      seats: 5,
      horsepower: 302,
      engine: "2.0L I4",
      acceleration: 4.8,
    },
  },
  {
    id: 26,
    image: "/F2.jpeg",
    name: "Mercedes E450 Convertible",
    price: 550,
    durationPrice: 3300,
    specs: {
      seats: 4,
      horsepower: 362,
      engine: "3.0L V6",
      acceleration: 5.1,
    },
  },
  {
    id: 27,
    image: "/F3.jpeg",
    name: "Mercedes E53 Convertible",
    price: 750,
    durationPrice: 4500,
    specs: {
      seats: 4,
      horsepower: 429,
      engine: "3.0L I6",
      acceleration: 4.5,
    },
  },
  {
    id: 28,
    image: "/F4.jpeg",
    name: "Mercedes G63",
    price: 1500,
    durationPrice: 9000,
    specs: {
      seats: 5,
      horsepower: 577,
      engine: "4.0L V8",
      acceleration: 4.5,
    },
  },
  {
    id: 29,
    image: "/F5.jpeg",
    name: "Mercedes G63 2025",
    price: 1800,
    durationPrice: 10800,
    specs: {
      seats: 5,
      horsepower: 577,
      engine: "4.0L V8",
      acceleration: 4.5,
    },
  },
  {
    id: 30,
    image: "/F6.jpeg",
    name: "Mercedes G800 Brabus",
    price: 2300,
    durationPrice: 13800,
    specs: {
      seats: 5,
      horsepower: 800,
      engine: "4.0L V8",
      acceleration: 4.2,
    },
  },
  {
    id: 31,
    image: "/F1.jpeg",
    name: "Mercedes S580 2024",
    price: 1000,
    durationPrice: 6000,
    specs: {
      seats: 5,
      horsepower: 496,
      engine: "4.0L V8",
      acceleration: 4.9,
    },
  },
  {
    id: 32,
    image: "/F2.jpeg",
    name: "Nissan Patrol 2025",
    price: 650,
    durationPrice: 3900,
    specs: {
      seats: 7,
      horsepower: 400,
      engine: "5.6L V8",
      acceleration: 5.6,
    },
  },
  {
    id: 33,
    image: "/F3.jpeg",
    name: "Porsche 718 Boxster",
    price: 900,
    durationPrice: 5400,
    specs: {
      seats: 2,
      horsepower: 300,
      engine: "2.0L I4",
      acceleration: 4.5,
    },
  },
  {
    id: 34,
    image: "/F4.jpeg",
    name: "Porsche Cayenne 2025",
    price: 1300,
    durationPrice: 7800,
    specs: {
      seats: 5,
      horsepower: 348,
      engine: "3.0L V6",
      acceleration: 5.7,
    },
  },
  {
    id: 35,
    image: "/F5.jpeg",
    name: "Porsche GTS4",
    price: 1600,
    durationPrice: 9600,
    specs: {
      seats: 5,
      horsepower: 453,
      engine: "4.0L V8",
      acceleration: 4.4,
    },
  },
  {
    id: 36,
    image: "/F6.jpeg",
    name: "Porsche GT3 RS",
    price: 4000,
    durationPrice: 24000,
    specs: {
      seats: 2,
      horsepower: 518,
      engine: "4.0L I6",
      acceleration: 3.2,
    },
  },
  {
    id: 37,
    image: "/F1.jpeg",
    name: "Porsche Panamera 2025",
    price: 1300,
    durationPrice: 7800,
    specs: {
      seats: 4,
      horsepower: 325,
      engine: "2.9L V6",
      acceleration: 5.3,
    },
  },
  {
    id: 38,
    image: "/F2.jpeg",
    name: "Porsche Targa 4",
    price: 1800,
    durationPrice: 10800,
    specs: {
      seats: 4,
      horsepower: 379,
      engine: "3.0L I6",
      acceleration: 4.4,
    },
  },
  {
    id: 39,
    image: "/F3.jpeg",
    name: "Range Rover SVR",
    price: 1000,
    durationPrice: 6000,
    specs: {
      seats: 5,
      horsepower: 575,
      engine: "5.0L V8",
      acceleration: 4.3,
    },
  },
  {
    id: 40,
    image: "/F4.jpeg",
    name: "Range Rover Vogue V8 2024",
    price: 1100,
    durationPrice: 6600,
    specs: {
      seats: 5,
      horsepower: 523,
      engine: "4.4L V8",
      acceleration: 5.2,
    },
  },
  {
    id: 41,
    image: "/F5.jpeg",
    name: "Range Rover Vogue V8 2025",
    price: 1300,
    durationPrice: 7800,
    specs: {
      seats: 5,
      horsepower: 523,
      engine: "4.4L V8",
      acceleration: 5.1,
    },
  },
  {
    id: 42,
    image: "/F6.jpeg",
    name: "Rolls Royce Cullinan 2024",
    price: 3300,
    durationPrice: 19800,
    specs: {
      seats: 5,
      horsepower: 563,
      engine: "6.75L V12",
      acceleration: 5.0,
    },
  },
  {
    id: 43,
    image: "/F1.jpeg",
    name: "Rolls Royce Cullinan Mansory",
    price: 4500,
    durationPrice: 27000,
    specs: {
      seats: 5,
      horsepower: 600,
      engine: "6.75L V12",
      acceleration: 4.8,
    },
  },
];
